spring:
  datasource:
    url: jdbc:mysql://db:3306/my_schema
    username: docker
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 80
spring-doc:
  paths-to-match:
    - /auth/**
    - /**
  swagger-ui:
    use-root-path: true
security:
  jwt:
    token:
      secret-key: 25745e
      expire-length: 3600000
cors:
  originPatterns: http://localhost:4200/